### ISSUE TITLE
inaccurate detection for image larger than 1000 pixel wide

### ISSUE THREAD

**Issue by am05mhz** [huoyijie/AdvancedEAST#10]
the code resize the image to max 736 pixel wide before processing the detection, this makes the text in the image (larger than 1000 pixel wide) too small to detect, and leads to inaccuracy.

if I change the resize process, i got resource exhausted error. do you have any ideas how to solve this?

**Comment by huoyijie** [comment]
you could try to resize the image to size which is larger then 736px(even larger then original size) and can be divided by 32px.

**Comment by am05mhz** [comment]
my image is 1920 x 1080, i have changed the resize part to simply return the original size. 1920 is dividable by 32, and got the resource exhausted error. seems like i have to get more RAM. thanks

**Comment by wulouzhu** [comment]
@huoyijie 
你好，请问可以把训练图片像检测时那样resize成宽高不一样 的尺寸吗？
