### ISSUE TITLE
Training error: could not broadcast input array from shape

### ISSUE THREAD

**Issue by wajahat57** [huoyijie/AdvancedEAST#12]
Hi
I am trying to run the training and am getting the following error:

```
 File "D:\AdvancedEAST\data_generator.py", line 33, in gen
    img

ValueError: could not broadcast input array from shape (720,1280,3) into shape (736,736,3)
```

Did you ever get such an error?
Any suggestions?
My data includes just a few images for merely initiating the training loop.

The tree structure of the files used for training is displayed below:

![untitled](https://user-images.githubusercontent.com/2271839/42585450-958eb840-852d-11e8-8dc9-6bdf3085c548.png)

**Comment by Wanjpeng** [comment]
> you should first run python preprocess.py, then python label.py, last 'python advanced_east.py'.

thanks a lot
