### ISSUE TITLE
想问问一些关于loss的问题

### ISSUE THREAD

**Issue by Banyueqin** [huoyijie/AdvancedEAST#14]
side_vertex_code_loss是表示什么loss，还有一个问题是预测出来的坐标是什么形式的（比如左上角，右下角坐标，还是其他形式）

**Comment by huoyijie** [comment]
side_vertex_code_loss：判断像素点是否边界像素以及头或者尾部边界的惩罚函数。输出层分别是1位score map, 是否在文本框内；2位vertex code，是否属于文本框边界像素以及是头还是尾；4位geo，是边界像素可以预测的2个顶点坐标。所有像素构成了文本框形状，只用边界像素去预测回归顶点坐标，边界像素定义为黄色和绿色框内部所有像素，是用所有的边界像素预测值的加权平均来预测头或尾的短边两端的两个顶点。
