### ISSUE TITLE
petrain 模型的精度

### ISSUE THREAD

**Issue by aoyingchen** [huoyijie/AdvancedEAST#15]
非常感谢您开源了代码，您是否尝试在ICDAR2015上测试过这个代码，相比较原始EAST模型，您的模型的精度召回大概是多少，十分感谢

**Comment by huoyijie** [comment]
只在icpr数据集做过实验，没有在其他数据集做对比测试哈

**Comment by xiiiiiiii** [comment]
你好，想问问你在icdar2015上的精度如何？

**Comment by xiiiiiiii** [comment]
想问一下精度和召回率怎么计算，可以提供一下方法吗？
