### ISSUE TITLE
merge layer 产生多个网络分支问题

### ISSUE THREAD

**Issue by KwangKa** [huoyijie/AdvancedEAST#16]
https://github.com/huoyijie/AdvancedEAST/blob/ba788240f2317afb4028404f56b1989499c6c4b3/network.py#L65-L70
这几行代码，会生成三个不同的feature merge layer网络分支，这是预期的结果吗？

可不可以这样直接生成7个output map：
`Conv2D(7, 1, padding='same', name='output_all')(self.g(cfg.feature_layers_num))`

**Comment by huoyijie** [comment]
不好意思一直比较忙没有查看，这个确实是一个早期没发现的bug......
