### ISSUE TITLE
关于side区域标签生成的问题

### ISSUE THREAD

**Issue by saicoco** [huoyijie/AdvancedEAST#19]
头尾按照属于第一个poly进行标记，但是初始map为0, 属于head-side的ith=0，属于tail-side的ith=1，no-side的ith=-1，如此标记的话，head-side与non-side的值都为0，这部分可视化出来会发现只有tail没有head，在训练过程中head的损失计算会出现错误。这里作者认为如何

**Comment by huoyijie** [comment]
你好，你这边能提供出现这种问题的图片吗，可以发到我邮箱，问题还是有点不太理解。谢谢
我邮箱yijie.huo@foxmail.com

**Comment by saicoco** [comment]
邮件已发，多谢回复

**Comment by wulouzhu** [comment]
@saicoco 
我也有这个疑问，请问答案是什么，谢谢
