### ISSUE TITLE
weight file error

### ISSUE THREAD

**Issue by RoGoSo** [huoyijie/AdvancedEAST#20]
when I use the file ‘east_model_weights_2T736.h5’, Error comes up. ValueError: You are trying to load a weight file containing 58 layers into a model with 30 layers. It seems the weight file does not match.

**Comment by huoyijie** [comment]
Caused by a bug-fix, if you update code recently, you need re-download the .h5 file from the link below. 
Link: https://pan.baidu.com/s/1KO7tR_MW767ggmbTjIJpuQ 
password: kpm2

**Comment by RoGoSo** [comment]
@huoyijie Thanks! It works!

**Comment by AkshadaShinde** [comment]
@huoyijie I don't  understand Chinese language. Can you please send direct link for downloading weights? is it free?

**Comment by RoGoSo** [comment]
> @huoyijie I don't understand Chinese language. Can you please send direct link for downloading weights? is it free?

It is a Cloud disk for sharing files， just like Google cloud disk. Enter the password and click the button you can download it. 
![1111](https://user-images.githubusercontent.com/11746911/67374640-0e0a8680-f5b4-11e9-8c9f-ef3bb0a6c5b6.png)
