### ISSUE TITLE
quad invalid with vertex num less then 4.

### ISSUE THREAD

**Issue by wqq19930507** [huoyijie/AdvancedEAST#21]
使用您的预训练模型做预测，测试了一张名片图片，报错，用您demo内的图片测试是没有问题的

**Comment by huoyijie** [comment]
这是warning信息，是说有一个文本框因为识别到的顶点数少于4个没有被召回，可以忽略。

**Comment by wqq19930507** [comment]
您好，您更改网络后，使用您预训练的模型测试您demo中的机动车驾驶证照片，已明显没有您demo中的效果了，会有十几个文本框因为识别到的顶点数少于4个没有被召回，只能检测出几个文本框，我想找一下原因，是否可以告诉我您更改了哪里，最好能提供下您未更改时的代码。

**Comment by huoyijie** [comment]
这个模型训练迭代的次数少，可能没有之前效果好。这个是代码变更处
https://github.com/huoyijie/AdvancedEAST/commit/aa6a1a65654a14d58e6ee25feb7ccf3c4fb51c68

**Comment by wqq19930507** [comment]
您好，这处更改不会对结果有实质性影响，我更改为您原始代码后，使用您原始预训练模型测试了您demo中的机动车驾驶图片，效果仍然很差，会有大概十个左右的文本框没有被召回，您demo中的结果展示图是基于这个预训练模型的吗？

**Comment by CRonaldo1997** [comment]
@wqq19930507   我也遇到了同样的问题，漏检了很多text，请问您是如何解决的？

**Comment by NormalAppler** [comment]
@wqq19930507 我也遇到了同样的问题，漏检了很多text，请问您是如何解决的？
