### ISSUE TITLE
quad invalid with vertex num less then 4

### ISSUE THREAD

**Issue by lss616263** [huoyijie/AdvancedEAST#28]
您好，下载您提供的预训练模型， 然后测试github上demo里面的身份证和机动车驾驶证，总是出现这个问题，并不能得出您原始效果。请问这是什么原因？

**Comment by lss616263** [comment]
只能识别很少的一部分，然后就是报这个问题quad invalid with vertex num less then 4

**Comment by huoyijie** [comment]
提供下载的模型文件是最近重新训练的，训练迭代次数少于之前的训练，可能效果没有之前好。你这边可以尝试自己训练一下。

这里有关于我的训练细节#27
https://github.com/huoyijie/AdvancedEAST/issues/27

quad invalid with vertex num less then 4的疑问可以看下这里#21
https://github.com/huoyijie/AdvancedEAST/issues/21

**Comment by lss616263** [comment]
Thanks.
