### ISSUE TITLE
相邻两行分不开

### ISSUE THREAD

**Issue by ccnankai** [huoyijie/AdvancedEAST#37]
@huoyijie   
请问下图中问题能解决吗？为什么我训练之后这种情况很多，相邻行都连接到一起了。谢谢

![img_2061 jpg_act](https://user-images.githubusercontent.com/33537489/47206543-7a5c1400-d3bb-11e8-818b-4c2bd21521e8.jpg)
![img_2061 jpg_predict](https://user-images.githubusercontent.com/33537489/47206547-7b8d4100-d3bb-11e8-8bad-21130aeedee6.jpg)
换成resnet会不会变好？

**Comment by tianzhuotao** [comment]
可以参考eccv那篇文章把四周都加上boundary

**Comment by tianzhuotao** [comment]
@ccnankai Accurate Scene Text Detection through Border Semantics Awareness and Bootstrapping

**Comment by ccnankai** [comment]
@tianzhuotao   好，多谢多谢

**Comment by snowwindy** [comment]
> @tianzhuotao 好，多谢多谢

你好，想问一下，你的问题解决没？另外，我还遇到一些其他问题，比如检测时没有发现头或尾，导致最后不能生成文本框，请问这样的问题您有没有遇到过？是怎么解决的？

**Comment by clw5180** [comment]
> > @tianzhuotao 好，多谢多谢
> 
> 你好，想问一下，你的问题解决没？另外，我还遇到一些其他问题，比如检测时没有发现头或尾，导致最后不能生成文本框，请问这样的问题您有没有遇到过？是怎么解决的？

同问

**Comment by wulouzhu** [comment]
同问

**Comment by xiiiiiiii** [comment]
> > @tianzhuotao 好，多谢多谢
> 
> 你好，想问一下，你的问题解决没？另外，我还遇到一些其他问题，比如检测时没有发现头或尾，导致最后不能生成文本框，请问这样的问题您有没有遇到过？是怎么解决的？

你好啊啊啊！想问一下相邻两行分不开的情况你解决了吗？

**Comment by xiiiiiiii** [comment]
> @tianzhuotao 好，多谢多谢

你好，想问一下，这个怎么给四周都加上边框，如果都加上边框的话，那模型的输出也要对应的发生变化是吗？

**Comment by xiiiiiiii** [comment]
> @ccnankai Accurate Scene Text Detection through Border Semantics Awareness and Bootstrapping



> 可以参考eccv那篇文章把四周都加上boundary

你好，想问一下，这个怎么给四周都加上边框，如果都加上边框的话，那模型的输出也要对应的发生变化是吗？
