### ISSUE TITLE
自己训练了模型却predict不出任何边框

### ISSUE THREAD

**Issue by Taylor-Rose** [huoyijie/AdvancedEAST#46]
你好，我用的数据集是tianchi ICPR的数据集 就是你分享的百度网盘的数据集，但是我根据preprocess label advanced_east 后，再predict，没有任何的边框检测出来，请问是有哪些可能？

**Comment by Fighting-JJ** [comment]
@Taylor-Rose 训练出来了？效果达到作者readme中展示的效果了吗？

**Comment by Taylor-Rose** [comment]
训练出来了

**Comment by Brave731** [comment]
训练时修改了什么地方吗，val_loss收敛到多少，为什么我没训练出来啊

**Comment by leigaoxiang** [comment]
我也出现这种情况
@Taylor-Rose
