### ISSUE TITLE
检测结果无头无尾

### ISSUE THREAD

**Issue by snowwindy** [huoyijie/AdvancedEAST#51]
@huoyijie 
您好，谢谢您代码的分享。我遇到一些问题，没找到头绪，想要咨询一下。
首先，我要检测的是自然场景下的文字，所以我对训练数据集进行了更改，使用的是ICDAR 2017的数据集和自己标注的数据集，后面找了一些图片进行测试。发现一些问题，有很多图片出现了有头无尾，有尾无头，无头无尾，以及相邻两行之间交叉，分不开的情况，可是我找不到原因以及怎么改善？可以给我一些建议吗？研三了，比较急，谢谢啦

![31 jpg_act](https://user-images.githubusercontent.com/29096197/52893770-2fbc9e00-31db-11e9-87e4-3d69829c0318.jpg)
![31 jpg_predict](https://user-images.githubusercontent.com/29096197/52893771-2fbc9e00-31db-11e9-826f-ac6db1a492aa.jpg)
![41 jpg_act](https://user-images.githubusercontent.com/29096197/52893773-30553480-31db-11e9-9d81-cc624f8d5f63.jpg)
![41 jpg_predict](https://user-images.githubusercontent.com/29096197/52893774-30553480-31db-11e9-85f6-d8f614ba23f2.jpg)

![8 jpg_act](https://user-images.githubusercontent.com/29096197/52893797-701c1c00-31db-11e9-9659-34c8f39db215.jpg)
![8 jpg_predict](https://user-images.githubusercontent.com/29096197/52893798-701c1c00-31db-11e9-9deb-2daba288d65a.jpg)

**Comment by Bachelorwangwei** [comment]
我也遇到了同样的问题，检测不全。不清楚三个阈值具体含义是什么？

**Comment by snowwindy** [comment]
@Bachelorwangwei 我感觉现在也是一脸懵，不知道怎么能让效果好一些？也不知道问题出哪儿

**Comment by Bachelorwangwei** [comment]
我今天按照作者的训练方法，重新训练了一下，效果还不错。
你先训练256大小的，其次训练384的，在训练384的时候，将上次训练得到的weights.h5 load进去，这样依次训练512,640,736的，结果会有明显提升。
作者之前的回答里面有具体的解释[https://github.com/huoyijie/AdvancedEAST/issues/27](url)，你可以按照这个方法重新训练一下。

**Comment by snowwindy** [comment]
@Bachelorwangwei 嗯嗯，好的，我尝试一下，谢谢啦~
把最佳的保存在saved_weights里面，然后依次load训练是吗？作者说设置cfg.initial_epoch =“ending_epoch”，这个ending是什么呀？

**Comment by Bachelorwangwei** [comment]
> @Bachelorwangwei 嗯嗯，好的，我尝试一下，谢谢啦~
> 把最佳的保存在saved_weights里面，然后依次load训练是吗？作者说设置cfg.initial_epoch =“ending_epoch”，这个ending是什么呀？

嗯，是的，依次训练进行微调。
cfg.initial_epoch 就是你训练上一个尺寸图片，得到最佳模型时候的epoch，在log里面会有显示。

**Comment by snowwindy** [comment]
@Bachelorwangwei 嗯嗯，好的，了解了，谢谢啦，我重新训练一下~

**Comment by snowwindy** [comment]
@Bachelorwangwei 不好意思，我遇到一些小问题，方便留个QQ或微信吗？

**Comment by Bachelorwangwei** [comment]
@snowwindy   微信发我邮箱 wangweixaut@foxmail.com

**Comment by luckyXZR** [comment]
@Bachelorwangwei 
你好！ 我也是在研究相同类型的问题，不是很懂怎么把好的结果保存在saved_weights里面，再接着训练，可以具体讲解一下吗？

**Comment by luckyXZR** [comment]
@snowwindy 你好！我要检测的图片和你发出来的有类似的地方，想问下你现在用这个网络训练的话，结果怎么样了呢？识别率高吗？

**Comment by xiiiiiiii** [comment]
同是研三的学生，同样焦急，可以加一下微信或者qq交流一下吗？

**Comment by snowwindy** [comment]
@xiiiiiiii 不好意思，我已经毕业了，所以这个现在没有继续做

**Comment by xiiiiiiii** [comment]
> @xiiiiiiii 不好意思，我已经毕业了，所以这个现在没有继续做

可以分享一下你当时做的时候怎么解决这个问题的方法吗？可以加你微信交流一下吗？我的微信是aabbcc281
