### ISSUE TITLE
如何训练

### ISSUE THREAD

**Issue by LiangHao92** [huoyijie/AdvancedEAST#6]
你好，能给一个稍微详细点的训练步骤么。想用自己的数据来训练试试

**Comment by LiangHao92** [comment]
请问训练的时候数据集必须是固定的尺寸么，如果要reshape原图，那原图的标注数据怎么办

**Comment by LiangHao92** [comment]
请问训练的时候数据集必须是固定的尺寸么，如果要reshape原图，那原图的标注数据怎么办。因为我训练的时候报如下的错误
`    x[i] = preprocess_input(img, mode='tf')
ValueError: could not broadcast input array from shape (3200,2400,3) into shape (736,736,3)
`
我下载了你的数据，看到你的数据也不是固定的尺寸，所以很疑惑

**Comment by wajahat57** [comment]
Thanks Liang,
I would also like some help in training my own data.
