### ISSUE TITLE
The issue of predict

### ISSUE THREAD

**Issue by simplify23** [huoyijie/AdvancedEAST#78]
I want to test the pre-train model 
the environment :
ubuntu16.04
python2.7
tensorflow==1.5.0

I put my test image in the demo,here is my command
 --python predict.py -p demo/1.jpg 

but i got error: 
![image](https://user-images.githubusercontent.com/39580716/56464664-c8141080-6420-11e9-934e-02e8ff698a2d.png)

please help me

**Comment by hcnhatnam** [comment]
Are you sure test image path?

**Comment by simplify23** [comment]
ye~p, I put my test image into the demo/ folder. Besides, the demo origin images will also got this error .

**Comment by Fan9** [comment]
I meet this error when i used python2.7.but when I use python3, the problem is solved. hope this helps you
