### ISSUE TITLE
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

### ISSUE THREAD

**Issue by magicxiaobai** [huoyijie/AdvancedEAST#91]
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

    8192/58889256 [..............................] - ETA: 38:30
   24576/58889256 [..............................] - ETA: 47:25
   40960/58889256 [..............................] - ETA: 39:50
   57344/58889256 [..............................] - ETA: 39:34Traceback (most recent call last):

i do not know how to solve it????

**Comment by lifloveyou** [comment]
which you put the vgg model in ,why i put it in ~/kreas/model,it is still downloading

**Comment by Asuna88** [comment]
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5 

它的默认下载路径是
/home/username/.keras/models/vgg16_weights_tf_dim_ordering_tf_kernels.h5
也就是说它是保存在当前用户的家目录下的隐藏目录.keras里面的models文件夹里面，可以从里面复制出来再显式使用。
